config/routes.rb
Rails.application.routes.draw do

  resources :investigations

  get 'pages/calendar'

  get 'assignments/show'

  get 'calendar/show'

  resources :events

  resources :clients

  resources :applicants

  devise_for :users
  
  devise_for :installs

  get 'jason/jasons_hang_out'

  get 'clients/edit'

  get 'clients/index'

  get 'clients/new'

  get 'clients/show'

  get 'about_us/about'

  get 'investigations/edit'

  get 'investigations/index'

  get 'investigations/new'

  get 'investigations/show'

  post 'investigations/new'
  
  get 'welcome/index'
  

   root 'welcome#index'

end

app/models/investigation.rb
class Investigation < ActiveRecord::Base
	belongs_to :user
	belongs_to :applicant
	belongs_to :client
end

app/controllers/investigations_controller.rb
class InvestigationsController < ApplicationController
  before_action :set_investigation, only: [:show, :edit, :update, :destroy]

  # GET /investigations
  # GET /investigations.json
  def index
    @investigations = Investigation.all
  end

  # GET /investigations/1
  # GET /investigations/1.json
  def show
  end

  # GET /investigations/new
  def new
    @investigation = Investigation.new
  end

  # GET /investigations/1/edit
  def edit
  end

  # POST /investigations
  # POST /investigations.json
  def create
    
    @investigation = Investigation.new(investigation_params)

    respond_to do |format|
      if @investigation.save
        format.html { redirect_to @investigation, notice: 'Investigation was successfully created.' }
        format.json { render :show, status: :created, location: @investigation }
      else
        format.html { render :new }
        format.json { render json: @investigation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investigations/1
  # PATCH/PUT /investigations/1.json
  def update
    respond_to do |format|
      if @investigation.update(investigation_params)
        format.html { redirect_to @investigation, notice: 'Investigation was successfully updated.' }
        format.json { render :show, status: :ok, location: @investigation }
      else
        format.html { render :edit }
        format.json { render json: @investigation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investigations/1
  # DELETE /investigations/1.json
  def destroy
    @investigation.destroy
    respond_to do |format|
      format.html { redirect_to investigations_url, notice: 'Investigation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investigation
      @investigation = Investigation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def investigation_params
      params.require(:investigation).permit(:applicant_id, :client_id, :user_badge_number, :status, :renewal, :comments)
    end
end

app/helpers/investigations_helper.rb
module InvestigationsHelper
end

app/views/investigations/_form.html.erb
  <% if @investigation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@investigation.errors.count, "error") %> prohibited this investigation from being saved:</h2>

      <ul>
      <% @investigation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <!-- Main -->
      <section class="wrapper style1">
        <div class="container">
          <div class="row 200%">
            <div class="4u 12u(narrower)">
              <div id="sidebar">

                <!-- Sidebar -->

                  <section>
                    <span class="image featured"><img src="/assets/banner.jpg" alt="" /></span>
                      
                      <%= form_tag("/applicants", method: "get") do %>
                      <%= label_tag(:search, "Search Applicants:") %>
                      <%= text_field_tag(:search) %>
                      <br>
                      <%= submit_tag("Search") %>
                    <% end %>
                    <br>
                      <p> This Form will help guide the Detective and keep track of pertinent information that is collected throughout the investigation. The Submit button will submit an Investigation to the Sergeant for Approval. </p>
                  </section>
              </div>
            </div>
            <div class="8u  12u(narrower) important(narrower)">
              <div id="content">

                <!-- Content -->

                  <article>
                    <header>
                      <%= form_for(@investigation) do |f| %>
                      <h2>New Investigation:</h2>
                      <p>Welcome Detective, lets begin a new investigation and submit it for review</p>
                    </header>
                      <div class="field">
                        <%= f.label :user_badge_number, "Badge Number" %><br>
                        <%= f.text_field :user_badge_number %>
                      </div>
                      <br>
                        <div class="field">
                          <%= f.label :comments %><br>
                          <%= f.text_area :comments, placeholder:"Comments cannot exceed 149 characters..."%>
                        </div>
                  </article>

              </div>
            </div>
          </div>
        </div>
      </section>
    <!-- Posts -->
      <section class="wrapper style1">
        <div class="container">
          <div class="row">
            <section class="6u 12u(narrower)">
              <div class="box post">
                <a href="#" class="image left"><img src="/assets/pic01.jpg" alt="" /></a>
                <div class="inner">
                    <div class="field">
                      <%= f.label :applicant_id, "Apllicant ID Number" %><br>
                      <%= f.number_field :applicant_id %>
                    </div>
                </div>
              </div>
            </section>
            <section class="6u 12u(narrower)">
              <div class="box post">
                <a href="#" class="image left"><img src="/assets/pic02.jpg" alt="" /></a>
                <div class="inner">
                    <div class="field">
                      <%= f.label :client_id %><br>
                      <%= f.number_field :client_id %>
                    </div>
                </div>
              </div>
            </section>
          </div>
          <div class="row">
            <section class="6u 12u(narrower)">
              <div class="box post">
                <a href="#" class="image left"><img src="/assets/pic03.jpg" alt="" /></a>
                <div class="inner">
                  <div class="field">
                    <%= f.label :status, "Application Status" %><br>
                                <%= f.select :status, [['Recommended','Recommended'],['Not Recommended','Not Recommended'],['-------------','Unsure'],['Pending','Pending'],['Temporary'],['Temporary'],['Withdrawn','Withdrawn']] %>
                  </div>
                </div>
              </div>
            </section>
            <section class="6u 12u(narrower)">
              <div class="box post">
                <a href="#" class="image left"><img src="/assets/pic04.jpg" alt="" /></a>
                <div class="inner">
                  <div class="field">
                    <%= f.label :renewal %><br>
                    <%= f.date_field :renewal %>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
      </section>

    <!-- CTA -->
      <section id="cta" class="wrapper style3">
        <div class="container">
          <header>
            <h2>CLICK HERE TO SUBMIT YOUR APPLICATION FOR REVIEW</h2>
              <div class="actions">
                <%= f.submit "Submit"%>
              </div>
          </header>
        </div>
      </section>
<% end %>

app/views/investigations/edit.html.erb
<!-- Nav -->
<nav id="nav">
  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
<ul>
  <li> <%= link_to "Home", root_path %></li>
  <li class="current">
      <a href="">Case Management</a>
    <ul>
      <li><%= link_to "New Case", new_investigation_path%></li>
      <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">Open Cases</a></li>
      <li>
        <a href="">Search Records</a>
        <ul>
          <li><%= link_to "Cases", investigations_path %> </li>
          <li ><%= link_to "Applicants", applicants_path %></li>
          <li><%= link_to "Clients", clients_path%></li>
          <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">All Detectives</a></li>
        </ul>
      </li>
      <li><%= link_to "Calendar", calendar_show_path %></li>
    </ul>
  </li>
  <li><%= link_to "Client", clients_new_path %></li>
  <li><%= link_to "Applicant", new_applicant_path%></li>
  <li><%= link_to "About Us", about_us_about_path %></li>
  <li><a href="#footer">Support</a></li>       
</ul>
</nav>
</div>

<h1>Editing Investigation</h1>

<%= render 'form' %>

<%= link_to 'Show', @investigation %> |
<%= link_to 'Back', investigations_path %>

app/views/investigations/index.html.erb
<!-- Nav -->
<nav id="nav">
  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
<ul>
  <li> <%= link_to "Home", root_path %></li>
  <li class="current">
      <a href="">Case Management</a>
    <ul>
      <li><%= link_to "New Case", new_investigation_path%></li>
      <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">Open Cases</a></li>
      <li>
        <a href="">Search Records</a>
        <ul>
          <li><%= link_to "Cases", investigations_path %> </li>
          <li ><%= link_to "Applicants", applicants_path %></li>
          <li><%= link_to "Clients", clients_path%></li>
          <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">All Detectives</a></li>
        </ul>
      </li>
      <li><%= link_to "Calendar", calendar_show_path %></li>
    </ul>
  </li>
  <li><%= link_to "Client", clients_new_path %></li>
  <li><%= link_to "Applicant", new_applicant_path%></li>
  <li><%= link_to "About Us", about_us_about_path %></li>
  <li><a href="#footer">Support</a></li>       
</ul>
</nav>
</div>
<p id="notice"><%= notice %></p>

    <!-- Main -->
      <section class="wrapper style1">
        <div class="container">
          <div class="row 200%">
            <div class="4u 12u(narrower)">
              <div id="sidebar">

                <!-- Sidebar -->
                <section>
                  <section>
                    <%= form_tag("/investigations", method: "get") do %>
                      <%= label_tag(:search, "Search Cases:") %>
                      <%= text_field_tag(:search) %>
                      <br>
                      <%= submit_tag("Search") %>
                    <% end %>
                    <br>
                  </section>
                      <span class="image featured"><img src="/assets/banner.jpg" alt="" /></span>
                    </footer>
                  </section>
              </div>
            </div>
            <div class="8u  12u(narrower) important(narrower)">
              <div id="content">

                <!-- Content -->

                  <article>
                    <header>
                      <h2>Case Records</h2>
                      <p>This table lists information about all investigations</p>
                    </header>
                    <table class="default">
                        <thead>
                          <tr>
                            <th>Badge#</th>
                            <th>Client ID</th>
                            <th>ID Number</th>
                            <th>Status</th>
                            <th colspan="3"></th>
                          </tr>
                        </thead>
                        <tbody>
                          <% @investigations.each do |investigation| %>
                            <tr>
                              <td><%= investigation.user_badge_number %></td>
                              <td><%= investigation.client_id %></td>
                              <td><%= investigation.applicant_id %></td>
                              <td><%= investigation.status%></td>
                              <td><%= link_to 'Show', investigation %></td>
                              <td><%= link_to 'Edit', edit_investigation_path(investigation) %></td>
                              <td><%= link_to 'Destroy', investigation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                            </tr>
                          <% end %>
                        </tbody>
                      </table>
                  </article>

              </div>
            </div>
          </div>
        </div>
      </section>
<br>

<%= link_to 'New Investigation', new_investigation_path %>

app/views/investigations/new.html.erb
<!-- Nav -->
<nav id="nav">
  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
<ul>
  <li> <%= link_to "Home", root_path %></li>
  <li class="current">
      <a href="">Case Management</a>
    <ul>
      <li><%= link_to "New Case", new_investigation_path%></li>
      <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">Open Cases</a></li>
      <li>
        <a href="">Search Records</a>
        <ul>
          <li><%= link_to "Cases", investigations_path %> </li>
          <li ><%= link_to "Applicants", applicants_path %></li>
          <li><%= link_to "Clients", clients_path%></li>
          <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">All Detectives</a></li>
        </ul>
      </li>
      <li><%= link_to "Calendar", calendar_show_path %></li>
    </ul>
  </li>
  <li><%= link_to "Client", clients_new_path %></li>
  <li><%= link_to "Applicant", new_applicant_path%></li>
  <li><%= link_to "About Us", about_us_about_path %></li>
  <li><a href="#footer">Support</a></li>       
</ul>
</nav>
</div>
<%= render 'form' %>


<%= link_to 'Back', investigations_path %>

app/views/investigations/show.html.erb
<!-- Nav -->
<nav id="nav">
  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
<ul>
  <li> <%= link_to "Home", root_path %></li>
  <li class="current">
      <a href="">Case Management</a>
    <ul>
      <li><%= link_to "New Case", new_investigation_path%></li>
      <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">Open Cases</a></li>
      <li>
        <a href="">Search Records</a>
        <ul>
          <li><%= link_to "Cases", investigations_path %> </li>
          <li ><%= link_to "Applicants", applicants_path %></li>
          <li><%= link_to "Clients", clients_path%></li>
          <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">All Detectives</a></li>
        </ul>
      </li>
      <li><%= link_to "Calendar", calendar_show_path %></li>
    </ul>
  </li>
  <li><%= link_to "Client", clients_new_path %></li>
  <li><%= link_to "Applicant", new_applicant_path%></li>
  <li><%= link_to "About Us", about_us_about_path %></li>
  <li><a href="#footer">Support</a></li>       
</ul>
</nav>
</div>

<p id="notice"><%= notice %></p>
    <!-- Main -->
      <section class="wrapper style1">
        <div class="container">
          <div id="content">

            <!-- Content -->

              <article>  
                <table class="default">
                <thead>
                  <tr>
                    <th>New Investigation Information:</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <td colspan="4">
                      </tr>
                    </tfoot>
                <tbody>
                  <tr>
                    <td>Applicant Id: </td>
                    <td><%= @investigation.applicant_id %> </td>
                    <td>Client ID: </td> 
                    <td><%= @investigation.client_id %>
                  </tr>
                <tr>
                  <td>User Badge Number</td>
                  <td><%= @investigation.user_badge_number%></td>
                  <td>Application Status</td>
                  <td><%= @investigation.status %></td> 
                </tr>
                <tr>
                  <td>Investigation Completed: </td>
                  <td><%= @investigation.created_at %></td>
                  <td>License Renewal: </td>
                  <td><%= @investigation.renewal%></td>
                </tr>
              </tbody>
            </table>
                  <strong>Comments:</strong>
                 <%= @investigation.comments %>
                </p>
              </article>
          </div>
        </div>
      </section>