config/routes.rb
Rails.application.routes.draw do

  resources :investigations

  get 'pages/calendar'

  get 'assignments/show'

  get 'calendar/show'

  resources :events

  resources :clients

  resources :applicants

  devise_for :users
  
  devise_for :installs

  get 'jason/jasons_hang_out'

  get 'clients/edit'

  get 'clients/index'

  get 'clients/new'

  get 'clients/show'

  get 'about_us/about'

  get 'investigations/edit'

  get 'investigations/index'

  get 'investigations/new'

  get 'investigations/show'

  post 'investigations/new'
  
  get 'welcome/index'
  

   root 'welcome#index'

end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
   
    has_many :investigations

	validates_presence_of :first_name, :last_name, :social, :dob
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
	validates :social, format: {with: /^(\d{3}-?\d{2}-?\d{4}|XXX-XX-XXXX)$/i, :multiline => true, on: :create}

	def self.search(search)
	  if search
	   @applicants = Applicant.where("first_name LIKE ?", "%#{search}%")
	  else
	    @applicants = Applicant.all
	  end
	end
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :set_applicant, only: [:show, :edit, :update, :destroy]

  # GET /applicants
  # GET /applicants.json
  def index
  @applicants = Applicant.search(params[:search])
  end

  # GET /applicants/1
  # GET /applicants/1.json
  def show 
  end
  
  # GET /applicants/new
  def new
    @applicant = Applicant.new
  end

  # GET /applicants/1/edit
  def edit
  end

  # POST /applicants
  # POST /applicants.json
  def create
    @applicant = Applicant.new(applicant_params)

    respond_to do |format|
      if @applicant.save
        format.html { redirect_to @applicant, notice: 'Applicant was successfully created.' }
        format.json { render :show, status: :created, location: @applicant }
      else
        format.html { render :new }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicants/1
  # PATCH/PUT /applicants/1.json
  def update
    respond_to do |format|
      if @applicant.update(applicant_params)
        format.html { redirect_to @applicant, notice: 'Applicant was successfully updated.' }
        format.json { render :show, status: :ok, location: @applicant }
      else
        format.html { render :edit }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicants/1
  # DELETE /applicants/1.json
  def destroy
    @applicant.destroy
    respond_to do |format|
      format.html { redirect_to applicants_url, notice: 'Applicant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant
      @applicant = Applicant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applicant_params
      params.require(:applicant).permit(:first_name, :last_name, :social, :email, :address, :line2, :city, :state, :zip, :phone1, :phone2, :company, :comments, :dob, :typeOfApplication)
    end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/views/applicants/_form.html.erb
<%= simple_form_for(@applicant) do |f| %>
  <%= f.error_notification %>
      <section class="wrapper style1">
        <div class="container">
          <div class="row 200%">
            <div class="3u 12u(narrower)">
              <div id="sidebar1">

                <!-- Sidebar 1 -->

                  <section>
                    <h3>The Rhode Island Gaming App</h3>
                    <p>Welcome to a one stop integrated application for Rhode Island Gaming employees. Please fill out the application below to begin the Background Investigation Process.</p>
                    <footer>
                      <span class="image featured"><img src="/assets/banner.jpg" alt="" /></span>

                    </footer>
                  </section>

                  <section>
                    <h3>Contact Information</h3>
                      <%= f.input :email, placeholder: "user@domain.com" %>
                      <%= f.input :phone1, label:"Primary Phone: ", as: :string, placeholder: "(XXX) XXX-XXXX" %>
                      <%= f.input :phone2, label: "Secondary Phone: ", as: :string, placeholder: "(XXX) XXX-XXXX"%> 
                      
                  </section>

              </div>
            </div>
            <div class="6u 12u(narrower) important(narrower)">
              <div id="content">

                <!-- Content -->

                  <article>
                    <header>
                      <h2>New Applicant</h2>
                      <p>Welcome lets begin a new application</p>
                    </header>
                      <%= f.input :first_name %>
                      <%= f.input :last_name %>
                      <%= f.input :social, placeholder: "###-##-####", label: "SSN or EIN Number" %>
                      <%= f.input :dob, label:"Date Of Birth", placeholder: "mm/dd/yyyy"%>
                      <%= f.input :company, label: "Affiliated Company" %>
                      <%= f.input :position, :collection => [['Cage Cashier','Cage Cashier'],['Dealer','Dealer'],['Key Employee','Key Employee'],['Security','Security'],['Table Games Supervisor','Table Games Supervisor'],['Other (specify in comments)','Other']] %>
                      <%= f.input :comments, placeholder:"149 character limit on each comment..." %>
                  </article>

              </div>
            </div>
            <div class="3u 12u(narrower)">
              <div id="sidebar2">

                <!-- Sidebar 2 -->

                  <section>
                    <h3>Address Information</h3>
                    
                        <%= f.input :address %>
                        <%= f.input :line2 %>
                        <%= f.input :city %>
                        <%= f.input :state %>
                        <%= f.input :zip %><br>
                        <h3> Application Type </h3> 
                    <div id="radio">
                      <div class="controls-row">
                           <%= f.collection_radio_buttons :typeOfApplication, [[true, 'Business |'] ,[false, '| Individual']], :first, :last %>
                      </div>
                    </div>
                    <div class="form-actions">
                      <%= f.button :submit, label:"Submit"%>
                    </div>
                  </section>
              </div>
            </div>
          </div>
        </div>
      </section>
<% end %>

app/views/applicants/edit.html.erb
<!-- Nav -->
<nav id="nav">
  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
<ul>
  <li> <%= link_to "Home", root_path %></li>
  <li>
      <a href="">Case Management</a>
    <ul>
      <li><%= link_to "New Case", new_investigation_path%></li>
      <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')" >Open Cases</a></li>
      <li>
        <a href="">Search Records</a>
        <ul>
          <li><%= link_to "Cases", investigations_path %> </li>
          <li ><%= link_to "Applicants", applicants_path %></li>
          <li><%= link_to "Clients", clients_path%></li>
          <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">All Detectives</a></li>
        </ul>
      </li>
      <li><%= link_to "Calendar", calendar_show_path %></li>
    </ul>
  </li>
  <li><%= link_to "Client", clients_new_path %></li>
  <li class="current"><%= link_to "Applicant", new_applicant_path%></li>
  <li><%= link_to "About Us", about_us_about_path %></li>
  <li><a href="#footer">Support</a></li>       
</ul>
</nav>
</div>
<p id="notice"><%= notice %></p>
<h1>Editing Applicant</h1>

<%= render 'form' %>

app/views/applicants/index.html.erb
<!-- Nav -->
<nav id="nav">
  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
<ul>
  <li> <%= link_to "Home", root_path %></li>
  <li>
      <a href="">Case Management</a>
    <ul>
      <li><%= link_to "New Case", new_investigation_path%></li>
      <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">Open Cases</a></li>
      <li>
        <a href="">Search Records</a>
        <ul>
          <li><%= link_to "Cases", investigations_path %> </li>
          <li ><%= link_to "Applicants", applicants_path %></li>
          <li><%= link_to "Clients", clients_path%></li>
          <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')S">All Detectives</a></li>
        </ul>
      </li>
      <li><%= link_to "Calendar", calendar_show_path %></li>
    </ul>
  </li>
  <li><%= link_to "Client", clients_new_path %></li>
  <li class="current"><%= link_to "Applicant", new_applicant_path%></li>
  <li><%= link_to "About Us", about_us_about_path %></li>
  <li><a href="#footer">Support</a></li>       
</ul>
</nav>
</div>
<p id="notice"><%= notice %></p>
    <!-- Main -->
      <section class="wrapper style1">
        <div class="container">
          <div class="row 200%">
            <div class="4u 12u(narrower)">
              <div id="sidebar">

                <!-- Sidebar -->

                  <section>
                    <%= form_tag("/applicants", method: "get") do %>
                      <%= label_tag(:search, "Search Applicants:") %>
                      <%= text_field_tag(:search) %>
                      <br>
                      <%= submit_tag("Search") %>
                    <% end %>
                    <br>
                  </section>
                  <section>
                    <footer>
                      <span class="image featured"><img src="/assets/banner.jpg" alt="" /></span>
                    </footer>
                  </section>

              </div>
            </div>
            <div class="8u  12u(narrower) important(narrower)">
              <div id="content">

                <!-- Content -->

                  <article>
                    <header>
                      <h2>Applicant Records</h2>
                      <p>This table lists information about all applicants</p>
                    </header>
                      <table class="default">
                        <thead>
                          <tr>
                            <th>First</th>
                            <th>Last</th>
                            <th>Social</th>
                            <th colspan="3"></th>
                          </tr>
                        </thead>

                        <tbody>
                          <% @applicants.each do |applicant| %>
                            <tr>
                              <td><%= applicant.first_name %></td>
                              <td><%= applicant.last_name %></td>
                              <td><%= applicant.social %></td>
                              <td><%= link_to 'Show', applicant %></td>
                              <td><%= link_to 'Edit', edit_applicant_path(applicant) %></td>
                              <td><%= link_to 'Destroy', applicant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                            </tr>
                          <% end %>
                        </tbody>
                      </table>

                  </article>

              </div>
            </div>
          </div>
        </div>
      </section>
<br>

<%= link_to 'New Applicant', new_applicant_path %>

app/views/applicants/new.html.erb
<!-- Nav -->
<nav id="nav">
  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
<ul>
  <li> <%= link_to "Home", root_path %></li>
  <li>
      <a href="">Case Management</a>
    <ul>
      <li><%= link_to "New Case", new_investigation_path%></li>
      <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">Open Cases</a></li>
      <li>
        <a href="">Search Records</a>
        <ul>
          <li><%= link_to "Cases", investigations_path %> </li>
          <li ><%= link_to "Applicants", applicants_path %></li>
          <li><%= link_to "Clients", clients_path%></li>
          <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">All Detectives</a></li>
        </ul>
      </li>
      <li><%= link_to "Calendar", calendar_show_path %></li>
    </ul>
  </li>
  <li><%= link_to "Client", clients_new_path %></li>
  <li class="current"><%= link_to "Applicant", new_applicant_path%></li>
  <li><%= link_to "About Us", about_us_about_path %></li>
  <li><a href="#footer">Support</a></li>       
</ul>
</nav>
</div>
<p id="notice"><%= notice %></p>
<%= render 'form' %>

<%= link_to 'Back', applicants_path %>

app/views/applicants/show.html.erb
<!-- Nav -->
<nav id="nav">
  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
<ul>
  <li> <%= link_to "Home", root_path %></li>
  <li>
      <a href="">Case Management</a>
    <ul>
      <li><%= link_to "New Case", new_investigation_path%></li>
      <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">Open Cases</a></li>
      <li>
        <a href="">Search Records</a>
        <ul>
          <li><%= link_to "Cases", investigations_path %> </li>
          <li ><%= link_to "Applicants", applicants_path %></li>
          <li><%= link_to "Clients", clients_path%></li>
          <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">All Detectives</a></li>
        </ul>
      </li>
      <li><%= link_to "Calendar", calendar_show_path %></li>
    </ul>
  </li>
  <li><%= link_to "Client", clients_new_path %></li>
  <li class="current"><%= link_to "Applicant", new_applicant_path%></li>
  <li><%= link_to "About Us", about_us_about_path %></li>
  <li><a href="#footer">Support</a></li>       
</ul>
</nav>
</div>
<p id="notice"><%= notice %></p>
    <!-- Main -->
      <section class="wrapper style1">
        <div class="container">
          <div id="content">

            <!-- Content -->

              <article>  
                <table class="default">
                <thead>
                  <tr>
                    <th>New Applicant Information:</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <td colspan="4">
                      </tr>
                    </tfoot>
                <tbody>
                  <tr>
                    <td>First Name: <%= @applicant.first_name %></td>
                    <td>Last Name: <%= @applicant.last_name %> </td>
                    <td>Email: <%= @applicant.email %></td>
                  </tr>
                <tr>
                  <td>Adress: <%= @applicant.address%></td>
                  <td>Line 2: <%= @applicant.line2 %></td>
                  <td>Social: <%= @applicant.social %><td>
                </tr>
                <tr>
                  <td>City: <%= @applicant.city %></td>
                  <td>State: <%@applicant.state %></td>
                  <td>Zip: <%= @applicant.zip%></td>
                </tr>
                <tr>
                  <td>Phone Primary: <%= @applicant.phone1 %></td>
                  <td>Applied For:  <%= @applicant.position%></td>
                  <td>Date of Birth:  <%= @applicant.dob %></td>
                <tr>
                  <td>Company: <%= @applicant.company %></td>
                  <td>Type: <%= @applicant.typeOfApplication %></td>
                  <td>Applicant ID: <%=@applicant.id%></td>
                </tr>
                </tbody>
                </table>
                </div>
                <p>
                  <strong>Comments:</strong>
                  <%= @applicant.comments %>
                </p>
              </article>
          </div>
        </div>
      </section>