config/routes.rb
Rails.application.routes.draw do

  resources :investigations

  get 'pages/calendar'

  get 'assignments/show'

  get 'calendar/show'

  resources :events

  resources :clients

  resources :applicants

  devise_for :users
  
  devise_for :installs

  get 'jason/jasons_hang_out'

  get 'clients/edit'

  get 'clients/index'

  get 'clients/new'

  get 'clients/show'

  get 'about_us/about'

  get 'investigations/edit'

  get 'investigations/index'

  get 'investigations/new'

  get 'investigations/show'

  post 'investigations/new'
  
  get 'welcome/index'
  

   root 'welcome#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :investigations 
	validates_presence_of :clientName, :address1, :city, :state, :message => "Missing a required field" 

	def self.search(search)
	  if search
	    @clients = Client.where("clientName LIKE ?", "%#{search}%")
	  else
	    @clients = Client.all
	  end
	end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.search(params[:search])
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:clientName, :clientPhone, :clientEmail, :address1, :address2, :city, :state, :zip)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for(@client) do |f| %>
  <%= f.error_notification %>
    <!-- Main -->
      <section class="wrapper style1">
        <div class="container">
          <div class="row 200%">
            <div class="8u 12u(narrower)">
              <div id="content">

                <!-- Content -->

                  <article>
                    <header>
                      <h2>New Client Application</h2>
                      <p>Welcome, lets begin the application</p>
                    </header>
                          <%= f.input :clientName, label: "Client Name: "%><br>
                          <%= f.input :address1, label:"Client Address: "%>
                          <%= f.input :address2, label:"Line 2: " %>
                          <%= f.input :city, label:"City: "%>
                          <%= f.input :state, label: "State: " %>
                          <%= f.input :zip, label:"Zip: "%>
                  </article>

              </div>
            </div>
            <div class="4u 12u(narrower)">
              <div id="sidebar">

                <!-- Sidebar -->

                  <section>
                    <h3>The Rhode Island Gaming Application</h3>
                    <p>Welcome to the online integrated application designed to process the licensing applications of employees seeking work at Rhode Island Casinos.</p>
                    <footer>
                      <span class="image featured"><img src="/assets/banner.jpg" alt="" /></span>
                    </footer>
                  </section>

                  <section>
                    <h3>Contact Information</h3>
                          <%= f.input :clientPhone, label:"Phone: " %>
                          <%= f.input :clientEmail, label:"Email: " %><br>
                      <div class="form-actions">
                        <%= f.button :submit %>
                      </div>
                  </section>

              </div>
            </div>
          </div>
        </div>
      </section>
  <%end%>

app/views/clients/edit.html.erb
<!-- Nav -->
<nav id="nav">
  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
<ul>
  <li> <%= link_to "Home", root_path %></li>
  <li>
      <a href="">Case Management</a>
    <ul>
      <li><%= link_to "New Case", new_investigation_path%></li>
      <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">Open Cases</a></li>
      <li>
        <a href="">Search Records</a>
        <ul>
          <li><%= link_to "Cases", investigations_path %> </li>
          <li ><%= link_to "Applicants", applicants_path %></li>
          <li><%= link_to "Clients", clients_path%></li>
          <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">All Detectives</a></li>
        </ul>
      </li>
      <li><%= link_to "Calendar", calendar_show_path %></li>
    </ul>
  </li>
  <li class = "current"><%= link_to "Client", clients_new_path %></li>
  <li><%= link_to "Applicant", new_applicant_path%></li>
  <li><%= link_to "About Us", about_us_about_path %></li>
  <li><a href="#footer">Support</a></li>       
</ul>
</nav>
</div>
<p id="notice"><%= notice %></p>
<h1>Editing Applicant</h1>  

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<!-- Nav -->
<nav id="nav">
  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
<ul>
  <li> <%= link_to "Home", root_path %></li>
  <li>
      <a href="">Case Management</a>
    <ul>
      <li><%= link_to "New Case", new_investigation_path%></li>
      <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">Open Cases</a></li>
      <li>
        <a href="">Search Records</a>
        <ul>
          <li><%= link_to "Cases", investigations_path %> </li>
          <li ><%= link_to "Applicants", applicants_path %></li>
          <li><%= link_to "Clients", clients_path%></li>
          <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">All Detectives</a></li>
        </ul>
      </li>
      <li><%= link_to "Calendar", calendar_show_path %></li>
    </ul>
  </li>
  <li class = "current"><%= link_to "Client", clients_new_path %></li>
  <li><%= link_to "Applicant", new_applicant_path%></li>
  <li><%= link_to "About Us", about_us_about_path %></li>
  <li><a href="#footer">Support</a></li>       
</ul>
</nav>
</div>

    <!-- Main -->
      <section class="wrapper style1">
        <div class="container">
          <div class="row 200%">
            <div class="4u 12u(narrower)">
              <div id="sidebar">

                <!-- Sidebar -->

                  <section>
                  <section>
                    <%= form_tag("/clients", method: "get") do %>
                      <%= label_tag(:search, "Search Clients:") %>
                      <%= text_field_tag(:search) %>
                      <br>
                      <%= submit_tag("Search") %>
                    <% end %>
                    <br>
                  </section>
                      <span class="image featured"><img src="/assets/banner.jpg" alt="" /></span>
                    </footer>
                  </section>
              </div>
            </div>
            <div class="8u  12u(narrower) important(narrower)">
              <div id="content">

                <!-- Content -->

                  <article>
                    <header>
                      <h2>Client Records</h2>
                      <p>This table lists information about all clients</p>
                    </header>
                        <table class="default">
                          <thead>
                            <tr>
                              <th>Name</th>
                              <th>Phone</th>
                              <th>Email</th>
                              <th colspan="3"></th>
                            </tr>
                          </thead>

                          <tbody>
                            <% @clients.each do |client| %>
                              <tr>
                                <td><%= client.clientName %></td>
                                <td><%= client.clientPhone %></td>
                                <td><%= client.clientEmail %></td>
                                <td><%= link_to 'Show', client %></td>
                                <td><%= link_to 'Edit', edit_client_path(client) %></td>
                                <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                              </tr>
                            <% end %>
                          </tbody>
                        </table>

                        <br>
                  </article>

              </div>
            </div>
          </div>
        </div>
      </section>
<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<!-- Nav -->
<nav id="nav">
  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
<ul>
  <li> <%= link_to "Home", root_path %></li>
  <li>
      <a href="">Case Management</a>
    <ul>
      <li><%= link_to "New Case", new_investigation_path%></li>
      <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">Open Cases</a></li>
      <li>
        <a href="">Search Records</a>
        <ul>
          <li><%= link_to "Cases", investigations_path %> </li>
          <li ><%= link_to "Applicants", applicants_path %></li>
          <li><%= link_to "Clients", clients_path%></li>
          <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">All Detectives</a></li>
        </ul>
      </li>
      <li><%= link_to "Calendar", calendar_show_path %></li>
    </ul>
  </li>
  <li class = "current"><%= link_to "Client", clients_new_path %></li>
  <li><%= link_to "Applicant", new_applicant_path%></li>
  <li><%= link_to "About Us", about_us_about_path %></li>
  <li><a href="#footer">Support</a></li>       
</ul>
</nav>
</div>


<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<!-- Nav -->
<nav id="nav">
  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
<ul>
  <li> <%= link_to "Home", root_path %></li>
  <li>
      <a href="">Case Management</a>
    <ul>
      <li><%= link_to "New Case", new_investigation_path%></li>
      <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">Open Cases</a></li>
      <li>
        <a href="">Search Records</a>
        <ul>
          <li><%= link_to "Cases", investigations_path %> </li>
          <li ><%= link_to "Applicants", applicants_path %></li>
          <li><%= link_to "Clients", clients_path%></li>
          <li><a onclick="return alert('Detective, you will need the administrator rights to make access this page. This function is meant for the Sergeant.')">All Detectives</a></li>
        </ul>
      </li>
      <li><%= link_to "Calendar", calendar_show_path %></li>
    </ul>
  </li>
  <li class = "current"><%= link_to "Client", clients_new_path %></li>
  <li><%= link_to "Applicant", new_applicant_path%></li>
  <li><%= link_to "About Us", about_us_about_path %></li>
  <li><a href="#footer">Support</a></li>       
</ul>
</nav>
</div>
<p id="notice"><%= notice %></p> 
</ul>
</nav>
</div>

    <!-- Main -->
      <section class="wrapper style1">
        <div class="container">
          <div id="content">

            <!-- Content -->

              <article>  
                <table class="default">
                <thead>
                  <tr>
                    <th>New Client Information:</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <td colspan="4">
                      </tr>
                    </tfoot>
                <tbody>
                  <tr>
                    <td>Client Name: <%= @client.clientName %></td>
                    <td>Client Phone: <%= @client.clientPhone %> </td>
                    <td>Client Email: <%= @client.clientEmail %></td>
                  </tr>
                <tr>
                  <td>Adress: <%= @client.address1 %></td>
                  <td>Line 2: <%= @client.address2 %></td>
                  <td>Client ID: <%= @client.id %> <td>
                </tr>
                <tr>
                  <td>City: <%= @client.city %></td>
                  <td>State: <%@client.state %></td>
                  <td>Zip: <%= @client.zip%></td>
                </tr>
                </tbody>
                </table>
                </div>
              </article>
          </div>
        </div>
      </section>
      